#模式 balance(均衡模式)、parallel(平行模式)
mode: parallel
#容器，可配置多个
containers:
  #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
  - address: http://192.168.31.233:5700
    #用户名
    username: admin
    #密码
    password: admin
    #2.9版本以上ClientID
    client_ID:
    #2.9版本以上Client Secret
    client_secret:
    #权重 balance模式下权重越高分得的ck越多，默认1
    weigth:  
    #单独对容器进行模式设置
    mode: parallel
    #限制容器ck数目
    limit: 9999

#自定义主题，支持本地、网络路径 
theme:  

#静态文件 便于自定义二维码页面时，引入css、js等文件
static: ./static

#管理员账户pin，有多个用'&'拼接
master: 

#数据库 支持sqlite3、mysql和postgres
#sqlite3 填路径，默认 ./.xdd
#mysql填user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
#postgres填host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
database:  

#企业微信推送key 
qywx_key:

#定时任务
daily_push:

#均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。
resident:

#自定义ua
user_agent:

#telegram bot token
telegram_bot_token:

#telegrame user id
telegram_user_id:

#接收通知的qq号
qquid:
#监听的群
qqgid:

#qq机器人群聊模式，默认私聊模式
qbot_public_mode: true

#新用户默认优先级
default_priority:

#更新资源是否不使用代理 默认false
no_ghproxy: true

#日常资产推送时间
daily_asset_push_cron:

#短信地址
SMS_Address:

#短信接口Token
SMS_Token:

#wskey定时转换时间
wskey_to_ptkey_cron:

repos:
  - git: https://github.com/shufflewzc/faker2.git